[package]
edition = "2021"
name = "day05"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.0"

[[bin]]
name = "day05"
path = "main.rs"
